### ISSUE TITLE
Could I use this with Meteor 1.3 via import?

### ISSUE THREAD

**Issue by thearabbit** [ovcharik/meteor-alertifyjs#4]
Could I use this with Meteor 1.3 via import?
Please example...

**Comment by ovcharik** [comment]
You can use [original package](https://github.com/MohammadYounes/AlertifyJS). I think you can install package something like:

1) Install package with NPM:

```
$ npm install alertifyjs --save
```

2) Import:

``` js
// something.js
// import package
import alertifyjs from 'alertifyjs'

// import styles
import 'alertifyjs/build/css/alertify.css';
import 'alertifyjs/build/css/themes/default.css';
```

Or you can import styles to css file:

``` css
/* something.css */
@import '{}/node_modules/alertifyjs/build/css/alertify.css';
@import '{}/node_modules/alertifyjs/build/css/themes/default.css';
```

For more information read [this](http://guide.meteor.com/using-npm-packages.html).

**Comment by thearabbit** [comment]
Look great, I will try this.
